server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bank}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml

jwt:
  secret: ${JWT_SECRET:changeit}
  expirationMs: ${JWT_EXP_MS:3600000}

cipher:
  key: ${CIPHER_KEY_BASE64:CHANGE_THIS_BASE64_32BYTES}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /docs/openapi.yaml
    path: /swagger-ui.html